Clean up BF downloads page for 5.3
ome/ome-release pull request #204
Opened 2016-10-13 11:29 UTC by hflynn

See https://trello.com/c/1srf2EZR/22-download-page-cleanup
This PR updates the doc and javadoc zip links, fixes the icon which had the wrong file format on it and removes the decoupled formats-common component from the Bio-Formats download page for the 5.3.0 release.

Will need to be tested during an RC I assume.

2016-10-17 12:12 UTC, sbesson commented
Closing this PR for 5.2.4 release. Can be reopened afterwards

2016-10-27 15:50 UTC, sbesson requested changes

2016-10-27 15:50 UTC, sbesson commented on bfgen.py
>          ("formats-bsd-test.jar", "artifacts/formats-bsd-test.jar"),
This also needs to be removed for 5.3.0-m1

2016-10-27 15:54 UTC, hflynn commented
@sbesson fix pushed

2016-10-27 16:01 UTC, sbesson commented
It turns out that as part of https://github.com/openmicroscopy/bioformats/commit/840dc9b8b456548453e8d213366e16ea2b62d929 I also modified the name of the `loci_tools` JAR with is now `loci-tools`... Could you add an extra commit to fix this for m1? I'll revert this in a follow-up PR.

2016-10-27 16:02 UTC, hflynn commented
@sbesson done

2016-10-27 16:04 UTC, sbesson commented
Thanks. https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-release-downloads/36/console now builds as expected.

2016-10-27 16:04 UTC, sbesson approved these changes

2016-10-28 20:37 UTC, merged